### ISSUE TITLE
Missing spec suites dependency

### ISSUE THREAD

**Issue by rene-aguirre** [compiler-dept/speck#20]
Current spec makefile misses to add a dependency for suites on library sources:

```
$(SUITES): $(SPECK_LIBS)
```

This allows to correct library errors quickly when developing new library additions.

**Comment by apfohl** [comment]
Thanks for the contribution. Please have a look at PR #19. The problem has already been discussed. I will make it more clear in the readme.

Of cause you can add that line to your makefile. But in Speck it would break things.

:beer:
